global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vits_alex'

