version: '3.5'
services:
  post_db:
    image: mongo:${POST_DB_VER}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
    container_name: monitoring_post_db

  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
    container_name: monitoring_ui_service

  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
    container_name: monitoring_post_service
  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - back_net
      - front_net
    container_name: monitoring_comment_service

volumes:
  post_db:

networks:
  back_net:
  front_net:
